# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/notebook',
                'doc_host': 'https://OscarIgM.github.io',
                'git_url': 'https://github.com/OscarIgM/mp3',
                'lib_path': 'notebook'},
  'syms': {'notebook.core': {'notebook.core.foo': ('core.html#foo', 'notebook/core.py')}}}
